# .coveralls.yml
service_name: github
repo_token: ${COVERALLS_REPO_TOKEN}   # ваш секрет из GitHub Actions
coverage_clover: coverage.xml             # clover-отчёт из phpunit
json_path: coverage.json            # сюда будет записан промежуточный JSON
exclude_no_stmt: true                    # не учитывать пустые файлы
entry_point: src                     # чтобы пути в отчёте резолвились относительно src/
